=== ziffitykishore/agilex/app/code/RocketWeb/ShoppingFeeds/etc/shoppingfeeds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2016 Rocket Web Inc. All rights reserved.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element type="feedType" name="feed" maxOccurs="unbounded" minOccurs="0">
                    <xs:unique name="uniqueFeedName">
                        <xs:selector xpath="feed"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="feedType">
        <xs:annotation>
            <xs:documentation>Feed type declaration</xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="label" type="xs:string" />
                <xs:element name="description" type="xs:string" />
            </xs:choice>

            <xs:element name="directives">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="directive" type="feedDirective" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueDirectiveName">
                    <xs:selector xpath="directive"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
    
            <xs:element name="default_product_columns" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="column" type="feedDefaultMapProductColumns" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
    
            <xs:element name="default_feed_config" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="general" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="name" type="xs:string" />
                                    <xs:element name="store_id" />
                                    <xs:element name="currency" />
                                    <xs:element name="feed_dir" />
                                    <xs:element name="apply_catalog_price_rules" type="xs:int" />
                                    <xs:element name="use_default_stock" type="xs:int" />
                                    <xs:element name="stock_attribute_code" />
                                    <xs:element name="use_qty_increments" type="xs:int" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="columns" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="product_columns" />
                                    <xs:element name="exclude_attributes" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="categories" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="locale" />
                                    <xs:element name="include_all_products" type="xs:int" />
                                    <xs:element name="provider_taxonomy_by_category" />
                                    <xs:element name="category_depth" type="xs:int" />
                                    <xs:element name="taxonomy_autocomplete_enabled" type="xs:int" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="filters" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="add_out_of_stock" />
                                    <xs:element name="product_types" />
                                    <xs:element name="attribute_sets" />
                                    <xs:element name="map_replace_empty_columns" />
                                    <xs:element name="find_and_replace" />
                                    <xs:element name="filters_output_limit" />
                                    <xs:element name="skip_column_empty" />
                                    <xs:element name="skip_price_above" minOccurs="0" />
                                    <xs:element name="skip_price_below" minOccurs="0" />
                                    <xs:element name="adwords_price_buckets" minOccurs="0" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="options" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="mode" type="xs:int" />
                                    <xs:element name="vary_categories" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="configurable" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="associated_products_mode" type="xs:int" />
                                    <xs:element name="add_out_of_stock" type="xs:int" />
                                    <xs:element name="inherit_parent_out_of_stock" type="xs:int" />
                                    <xs:element name="associated_products_link_add_unique" />
                                    <xs:element name="attribute_merge_value_separator" />
                                    <xs:element name="configurable_map_inherit" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="grouped" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="associated_products_mode" type="xs:int" />
                                    <xs:element name="add_out_of_stock" type="xs:int" />
                                    <xs:element name="associated_products_link_add_unique" type="xs:int" />
                                    <xs:element name="price_display_mode" type="xs:int" />
                                    <xs:element name="grouped_map_inherit" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="bundle" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="associated_products_mode" type="xs:int" />
                                    <xs:element name="combined_weight" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="shipping" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="methods" />
                                    <xs:element name="country" />
                                    <xs:element name="weight_column" />
                                    <xs:element name="only_minimum" />
                                    <xs:element name="only_free_shipping" />
                                    <xs:element name="add_tax_to_price" />
                                    <xs:element name="by_region" />
                                    <xs:element name="country_with_region" />
                                    <xs:element name="cache_enabled" />
                                    <xs:element name="ttl" />
                                    <xs:element name="carrier_realtime" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="schedule" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="batch_mode" />
                                    <xs:element name="batch_limit" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="ftp" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="mode" />
                                    <xs:element name="path" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="promotions" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="enabled"/>
                                    <xs:element name="provider_widget"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="output_params" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="default_value" />
                                    <xs:element name="delimiter" />
                                    <xs:element name="enclose_cell" />
                                    <xs:element name="enclose_escape" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="file" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="feed" minOccurs="0" maxOccurs="1"/>
                                    <xs:element name="log" minOccurs="0" maxOccurs="1"/>
                                    <xs:element name="promotion" minOccurs="0" maxOccurs="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" />
        <xs:attribute type="xs:string" name="translate" />
        <xs:attribute type="xs:string" name="taxonomyProvider" />
    </xs:complexType>

    <xs:complexType name="feedDirective">
        <xs:annotation>
            <xs:documentation>Feed directive</xs:documentation>
        </xs:annotation>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="label" type="xs:string" minOccurs="1" />
            <xs:element name="renderer">
                <xs:complexType>
                    <xs:attribute name="type" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="mappers">
                <xs:complexType>
                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                        <xs:element name="mapper">
                            <xs:complexType>
                                <xs:sequence minOccurs="0">
                                    <xs:element name="configuration">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:attribute name="name" type="xs:string" use="required" />
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="for" type="xs:string" default="default" />
                                <xs:attribute name="type" use="required" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="filter" type="xs:boolean" default="false" />
                </xs:complexType>
            </xs:element>
            <xs:element name="formatters">
                <xs:complexType>
                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                        <xs:element name="formatter">
                            <xs:complexType>
                                <xs:attribute name="for" type="xs:string" default="default" />
                                <xs:attribute name="type" use="required" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="param" type="xs:string" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="allow_output_limit" type="xs:boolean" default="false" />
    </xs:complexType>

    <xs:complexType name="feedDefaultMapProductColumns">
        <xs:annotation>
            <xs:documentation>Feed default product columns map</xs:documentation>
        </xs:annotation>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="column" type="xs:string" />
            <xs:element name="order" type="xs:int" />
            <xs:element name="param" type="xs:string" />
        </xs:choice>
        <xs:attribute type="xs:string" name="attribute" />
    </xs:complexType>
</xs:schema>

=== ziffitykishore/agilex/app/code/RocketWeb/ShoppingFeeds/etc/shoppingfeeds.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© 2016 Rocket Web Inc. All rights reserved.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="urn:magento:module:RocketWeb_ShoppingFeeds:etc/shoppingfeeds.xsd">
    <feed name="generic" translate="label,description" 
          taxonomyProvider="RocketWeb\ShoppingFeeds\Model\Taxonomy\Type\Generic">
        <label>Generic</label>
        <description>Generic feed type.</description>

        <directives>
            <directive name="directive_static_value">
                <label>Static Value</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\StaticValue" />
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\StaticValue" />
                </mappers>
            </directive>
            <directive name="directive_id">
                <label>Product Id</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\ProductId" />
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\Id" />
                </mappers>
                <param>0</param>
            </directive>
            <directive name="directive_url">
                <label>Product URL</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\ProductUrl" />
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\Url" />
                    <mapper for="configurable_child grouped_child bundle_child"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Configurable\Associated\Url" />
                </mappers>
                <param><![CDATA[]]></param>
            </directive>
            <directive name="directive_price">
                <label>Price</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\ProductPrice" />
                <mappers filter="true">
                    <mapper for="default" type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\Price" />
                    <mapper for="configurable"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Configurable\Price" />
                    <mapper for="grouped"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Grouped\Price" />

                </mappers>
                <formatters>
                    <formatter type="RocketWeb\ShoppingFeeds\Model\Product\Formatter\Price\Currency" />
                </formatters>
                <param>1</param>
            </directive>
            <directive name="directive_image_link">
                <label>Product Image URL</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\ProductImage" />
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\ImageLink" />
                </mappers>
            </directive>
            <directive name="directive_additional_image_link">
                <label>Product Additional Images URLs</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\ProductImageAdditional" />
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\AdditionalImageLink" />
                </mappers>
                <param>image</param>
            </directive>
            <directive name="directive_category_image_link">
                <label>Product Category Image URL</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\HelpMessage" />
                <param>First category found with an image is been used.</param>
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\CategoryImageLink" />
                </mappers>
            </directive>
            <directive name="directive_sale_price">
                <label>Sale Price</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\ProductPrice" />
                <mappers filter="true">
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\SalePrice" />
                    <mapper for="configurable grouped"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Configurable\SalePrice" />
                </mappers>
                <formatters>
                    <formatter type="RocketWeb\ShoppingFeeds\Model\Product\Formatter\Price\Currency"/>
                </formatters>
                <param>1</param>
            </directive>
            <directive name="directive_sale_price_effective_date">
                <label>Sale Price Date Range</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\HelpMessage" />
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\SalePriceEffectiveDate" />
                    <mapper for="configurable grouped bundle"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Configurable\SalePriceEffectiveDate" />
                </mappers>
                <param>Computes the start and end dates of special price. If end date is not specified, defaults to one year.</param>
            </directive>
            <directive name="directive_availability">
                <label>Availability</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\HelpMessage" />
                <mappers filter="true">
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\Availability" />
                    <mapper for="configurable bundle"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Configurable\Availability" />
                    <mapper for="grouped"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Grouped\Availability" />
                    <mapper for="configurable_child grouped_child bundle_child"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Configurable\Associated\Availability" />
                </mappers>
                <param><![CDATA[Computes the product availability: in stock / out of stock. See additional setting <a href="#" data-tab-id="#feed_tabs_general">Use default Stock Statuses</a>]]></param>
            </directive>
            <directive name="directive_quantity">
                <label>Inventory Count</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\ProductQuantity" />
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\Quantity" />
                    <mapper for="configurable grouped bundle"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Configurable\Quantity" />
                </mappers>
                <param>0</param>
            </directive>
            <directive name="directive_expiration_date">
                <label>Product Expiration in Feed</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\Expiration" />
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\ExpirationDate" />
                </mappers>
                <param>7</param>
            </directive>
            <directive name="directive_variant_attributes" allow_output_limit="true">
                <label>Variant Attributes</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\VariantAttributes" />
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\VariantAttributes" />
                    <mapper for="configurable grouped bundle"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Configurable\VariantAttributes" />
                </mappers>
            </directive>
            <directive name="directive_product_review_average">
                <label>Product Review Average</label>
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\ProductReviewAverage" />
                </mappers>
            </directive>
            <directive name="directive_product_review_count">
                <label>Product Review Count</label>
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\ProductReviewCount" />
                </mappers>
            </directive>
            <directive name="directive_concatenate" allow_output_limit="true">
                <label>Concatenate Attributes</label>
                <renderer type="RocketWeb\ShoppingFeeds\Block\Adminhtml\Feed\Edit\Form\Options\Renderer\Concatenate" />
                <mappers>
                    <mapper type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Simple\Concatenate" />
                    <mapper for="configurable_child"
                            type="RocketWeb\ShoppingFeeds\Model\Product\Mapper\Generic\Configurable\Associated\Concatenate" />
                    <mapper for="grouped_child"
